### ISSUE TITLE
IClient doesn't seem to be threadsafe

### ISSUE THREAD

**Issue by dilation** [openshift/openshift-restclient-java#264]
`IClient` (as created by `ClientBuilder`) doesn't seem to be threadsafe:

```scala
scala> val client = new ClientBuilder("...").usingToken("...").build()
client: com.openshift.restclient.IClient = com.openshift.internal.restclient.DefaultClient@83f7f27a

scala> val (f1, f2) = (Future { client.get[IProject](ResourceKind.PROJECT, "nokia", "nokia") }, Future { client.get[IProject](ResourceKind.PROJECT, "nokia", "nokia") })
f1: scala.concurrent.Future[com.openshift.restclient.model.IProject] = List()
f2: scala.concurrent.Future[com.openshift.restclient.model.IProject] = List()

scala> f1
res11: scala.concurrent.Future[com.openshift.restclient.model.IProject] = Success({"kind" : "Project", "apiVersion" : "v1", ..., "status" : {"phase" : "Active"}})

scala> f2
res12: scala.concurrent.Future[com.openshift.restclient.model.IProject] = Failure(java.lang.NullPointerException)

scala> scala.concurrent.Await.result(f2, 1.seconds)
java.lang.NullPointerException
  at com.openshift.internal.restclient.ApiTypeMapper.lambda$endpointFor$1(ApiTypeMapper.java:95)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
  at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
  at com.openshift.internal.restclient.ApiTypeMapper.endpointFor(ApiTypeMapper.java:96)
  at com.openshift.internal.restclient.ApiTypeMapper.isSupported(ApiTypeMapper.java:117)
  at com.openshift.internal.restclient.URLBuilder.buildWithNamespaceInPath(URLBuilder.java:145)
  at com.openshift.internal.restclient.URLBuilder.build(URLBuilder.java:132)
  at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:210)
  at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:194)
  at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:183)
  at com.openshift.internal.restclient.DefaultClient.get(DefaultClient.java:291)
  at $anonfun$2.apply(<console>:25)
  at $anonfun$2.apply(<console>:25)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

At first glance, the problematic code seems to be in `com.openshift.internal.restclient.ApiTypeMapper#init()`:

```java
if(initialized.compareAndSet(false, true)) {
	try {
		List<VersionedApiResource> resourceEndpoints = new ArrayList<>();
                // ...
		this.resourceEndpoints = resourceEndpoints;
	}catch(Exception e) {
		initialized.set(false);
		throw e;
	}
}
```

This doesn't seem to be threadsafe, thus another thread can see `initialized` as `true`, and `resourceEndpoints` still as `null`. Would we lose anything if `init` would be simply `synchronized`? The client is currently blocking anyway... (but see #256). (The alternative is of course to fix the lazy initialization with the CAS, but that's obviously harder to get right.)

**Comment by jcantrill** [comment]
There is probably no specific reason 'init' could not be synchronized other then it would lock the entire object.  Given we have no specific performance requirements, this is not an immediate concern.

**Comment by dilation** [comment]
Ok, please see pull request #265.

**Comment by jcantrill** [comment]
Pushed out in the latest 5.5.0 snapshot
