### ISSUE TITLE
Is it possible to access Openshift instance behind proxy?

### ISSUE THREAD

**Issue by vladfau** [openshift/openshift-restclient-java#328]
Hello, 

I'm trying to warp this client into Maven plugin for use in our organization, which has set of Openshift clusters, located behind the proxy.

When, I'm try to access it, I'm getting:

     Caused by: java.net.ConnectException: Failed to connect to <fqdn>/<ip>
     at okhttp3.internal.io.RealConnection.connectSocket (RealConnection.java:187)
     at okhttp3.internal.io.RealConnection.buildConnection (RealConnection.java:170)
     at okhttp3.internal.io.RealConnection.connect (RealConnection.java:111)

I set proxy in system and in Maven as well, also exported environment variables, but this doesn't seem to help. 

UPD: higher in the stack I see: `Caused by: com.openshift.restclient.OpenShiftException: Unable to read endpoint <myhttpfqdn>/api`

Any ideas?

**Comment by vladfau** [comment]
This is the code:

        IClient client = new ClientBuilder(openshiftEndpoint).build();
        client.getAuthorizationContext().setToken(openshiftToken);
        client.list(ResourceKind.PROJECT).forEach(x -> getLog().info(x.toString()));


Also, I tried the following thing:

        IClient client = new ClientBuilder(openshiftEndpoint).build();
        client.getAuthorizationContext().setToken(openshiftToken);
        getLog().info(client.getOpenShiftAPIVersion())

And received (after successful of printing `v1`):

```
Exception in thread "OkHttp Dispatcher" Exception in thread "OkHttp Dispatcher" java.lang.NoClassDefFoundError: okhttp3/internal/http/CacheStrategy$Factory
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:207)
	at okhttp3.RealCall.getResponse(RealCall.java:243)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:54)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
```

**Comment by vladfau** [comment]
Seems like it's not, so I implemented it on my own: https://github.com/openshift/openshift-restclient-java/compare/master...vladfau:feature/better-okhttp-proxy-support

**Comment by adietish** [comment]
great, stuff! I created a pull request for your changes at https://github.com/openshift/openshift-restclient-java/pull/329/files

**Comment by adietish** [comment]
@vladfau Is there any chance that you'd have some unit test for this? I checked and we unfortunately dont have anything for the build yet. It should be pretty simple though, I'd mock the okhttp-builder and verify that the setters for the proxy arguments are set if (and only if) the clientBuilder has such settings.

**Comment by vladfau** [comment]
@adietish I will try to do it this week, will push to PR branch

**Comment by vladfau** [comment]
@adietish @jcantrill submitted tests in PR, please take a look and let me know if it's ok

**Comment by adietish** [comment]
the PR at https://github.com/openshift/openshift-restclient-java/pull/329/files was merged. In this sense this feature request was fullfilled. Resolving it. 
@vladfau thanks a lot, kudos!
