### ISSUE TITLE
Exception while initializing the client

### ISSUE THREAD

**Issue by vers85** [openshift/openshift-restclient-java#343]
Hi all,

I am using version 6.1.1.Final and noticed that every time i start the application, the following exception is being thrown. The app is working fine, but the logs are polluted with this. I used to work on version 5 and this was not thrown for sure. I cannot change the permissions on openshift itself to allow anonymous access to this endpoint. 

Exception in thread "OkHttp Dispatcher" com.openshift.restclient.authorization.ResourceForbiddenException: User "system:anonymous" cannot "get" on "/version/openshift" User "system:anonymous" cannot "get" on "/version/openshift"
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:106)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:66)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by adietish** [comment]
Assuming that your openshift cluster didn't change I'm not all sure about the reasons or workarounds for this. 
@jcantrill dare to comment please?

**Comment by jcantrill** [comment]
This would be the same as a raw curl of the version endpoint, but I don't know without further investigation.  Maybe the endpoint no longer exists, but I have not tried recently.

**Comment by adietish** [comment]
issue #412 noticed that the ```DefaultClient``` was eagerly requesting kube- and openshift version upon instantiation. This was fixed in PR #413 and thus shouldnt happen any more. Closing.
