### ISSUE TITLE
does not run with java 11

### ISSUE THREAD

**Issue by adietish** [openshift/openshift-restclient-java#357]
given that java 10 went EOF we should now make sure openshift-restclient-java runs with java 11.
Currently the following exception occurs:
```

java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
--
at com.openshift.restclient.utils.Base64Coder.encode(Base64Coder.java:43)
at com.openshift.restclient.utils.Base64Coder.encode(Base64Coder.java:55)
at com.openshift.internal.restclient.okhttp.BasicChallangeHandler.handleChallange(BasicChallangeHandler.java:47)
at com.openshift.internal.restclient.okhttp.OpenShiftAuthenticator$1.authenticate(OpenShiftAuthenticator.java:91)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:294)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:160)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:55)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at com.openshift.internal.restclient.okhttp.OpenShiftAuthenticator.tryAuth(OpenShiftAuthenticator.java:97)
at com.openshift.internal.restclient.okhttp.OpenShiftAuthenticator.authenticate(OpenShiftAuthenticator.java:59)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:294)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:160)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:55)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:298)
at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:274)
at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:238)
at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:219)
at com.openshift.internal.restclient.DefaultClient.get(DefaultClient.java:400)
at com.openshift.internal.restclient.authorization.AuthorizationContext.isAuthorized(AuthorizationContext.java:63)
at org.jboss.tools.openshift.core.connection.Connection.authorize(Connection.java:237)
at org.jboss.tools.openshift.core.connection.Connection.connect(Connection.java:226)
at org.jboss.tools.openshift.internal.cdk.server.core.listeners.ConfigureDependentFrameworksListener.configureOpenshift(ConfigureDependentFrameworksListener.java:115)
at org.jboss.tools.openshift.internal.cdk.server.core.listeners.ConfigureDependentFrameworksListener.configureFrameworks(ConfigureDependentFrameworksListener.java:73)
at org.jboss.tools.openshift.internal.cdk.server.core.listeners.ConfigureDependentFrameworksListener$1.run(ConfigureDependentFrameworksListener.java:60)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter cannot be found by org.jboss.tools.openshift.client_3.6.0.AM1-v20181026-0330-B4105
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 36 more
```

**Comment by jeffmaury** [comment]
Yes the xml.ws has been removed from Java11, need to add as a dependency

**Comment by adietish** [comment]
@jeffmaury alternatively (and I think even better) is to use java.util.Base64 which was introduced in java8, which we require anyhow.

**Comment by adietish** [comment]
@jeffmaury please review #358

**Comment by adietish** [comment]
openshift-restclient-java now runs flawlessly with java 11. Closing.
