### ISSUE TITLE
NotFoundException on thread "OkHttp Dispatcher"

### ISSUE THREAD

**Issue by rbocanegra** [openshift/openshift-restclient-java#373]
Hi!
I have a basic code that creates a client and lists the pods like the following:

```
String url = "https://192.168.34.42:8443";
String projectName = "myproject";
String bearerToken = "<The Token>";
IClient client = new ClientBuilder(url).usingToken(bearerToken).build();
List<IPod> pods = client.list(ResourceKind.POD, projectName);
pods.forEach(p -> System.out.println(p.getName()));
```
The point is that the code works fine, but on the console I get the following exception:
```
Exception in thread "OkHttp Dispatcher" com.openshift.restclient.NotFoundException:  
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:113)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:66)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Inside `ResponseCodeInterceptor.intercept` the local response is `Response{protocol=http/1.1, code=404, message=Not Found, url=https://192.168.34.42:8443/version/openshift}`.

I am using minishift v1.32.0+009893b and openshift-restclient-java-7.0.0.Final on a Windows 10 machine with jdk8u191.

Thanks for your work.

**Comment by Ladicek** [comment]
I'm seeing this problem as well. It turns out that in some environments (I'm seeing it on Minishft 1.32.0, using the CentOS image 1.15.0, running OKD 3.11.0), the `/version/openshift` endpoint does return a 404 response:

```bash
lthon@argondie:~$ http https://192.168.99.102:8443/version/openshift
HTTP/1.1 404 Not Found
Cache-Control: no-store
Content-Length: 84
Content-Type: application/json
Date: Fri, 15 Mar 2019 10:17:26 GMT

{
    "paths": [
        "/apis",
        "/metrics",
        "/swagger-ui/",
        "/version"
    ]
}
```

While in some other environments (regular OCP cluster), it returns the expected response:

```bash
lthon@argondie:~$ http https://<URL redacted>/version/openshift
HTTP/1.1 200 OK
Audit-Id: <UUID redacted>
Cache-Control: no-store
Content-Length: 209
Content-Type: application/json
Date: Fri, 15 Mar 2019 10:18:16 GMT

{
    "buildDate": "2018-11-09T15:12:26Z",
    "compiler": "",
    "gitCommit": "647ac05cc9",
    "gitTreeState": "",
    "gitVersion": "v3.11.43",
    "goVersion": "",
    "major": "3",
    "minor": "11+",
    "platform": ""
}
```

As it seems the `kubernetesVersion` and `openShiftVersion` fields aren't used anywhere in the client itself (there's just a public getter, `equals` and `hashCode`), I propose that the error is simply ignored. A warning still makes sense, but without that ugly stacktrace.

**Comment by adietish** [comment]
@Ladicek awesome catch! thx
