### ISSUE TITLE
Question about scaling container

### ISSUE THREAD

**Issue by paravatha** [openshift/openshift-restclient-java#382]
Hi, I am trying to scale a container up and down as per the example in 
https://github.com/openshift/openshift-restclient-java/blob/4db8375aac177abd94c4e301f0a91f63d2e1ba68/src/test/java/com/openshift/internal/restclient/api/capabilities/ScaleCapabilityIntegrationTest.java

My code snippet:

        IReplicationController replicationController = new ResourceFactory(client).create("v1", ResourceKind.REPLICATION_CONTROLLER);
        ((ReplicationController) replicationController).setName(containerName);
        ((ReplicationController) replicationController).setNamespace(projectName);

        IScale result = replicationController.accept(new CapabilityVisitor<IScalable, IScale>() {

            @Override
            public IScale visit(IScalable capability) {
                int replicas = 0;
                if (count == 0) {
                    replicas = 1;
                } else if (count == 1) {
                    replicas = 0;
                }
                capability.getName();
                return capability.scaleTo(replicas);
            }
        }, null);

        int updatedReplicas = result.getSpecReplicas();

I am getting
**com.openshift.restclient.NotFoundException: replicationcontrollers/scale.autoscaling "test" not found**

Here is the full stack trace:

com.openshift.restclient.NotFoundException: replicationcontrollers/scale.autoscaling "test-cecl" not found replicationcontrollers/scale.autoscaling "test" not found

	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:113)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:66)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:293)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:267)
	at com.openshift.internal.restclient.api.capabilities.ScaleCapability.scaleTo(ScaleCapability.java:66)
	at com.dfs.dnd.training.coordinator.api.OCPRestClientTest$1.visit(OCPRestClientTest.java:72)
	at com.dfs.dnd.training.coordinator.api.OCPRestClientTest$1.visit(OCPRestClientTest.java:61)

Any idea what's wrong?

**Comment by jcantrill** [comment]
The answer is in your stack:

`com.openshift.restclient.NotFoundException: replicationcontrollers/scale.autoscaling "test" not found`  Do you have an rc with the given name?  `oc get rc -n $projectnamespace`
