### ISSUE TITLE
StackOverflowError while trying to execute request without OAUTH token

### ISSUE THREAD

**Issue by vachillo** [openshift/openshift-restclient-java#415]
Tried executing a request after providing just a username and password and got this. The stack trace is repeated a few hundred times. After providing an OAUTH token to the client builder it works fine.

`Caused by: java.lang.StackOverflowError: null
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538) ~[na:na]
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:174) ~[na:na]
	at java.base/java.net.URLStreamHandler.toExternalForm(URLStreamHandler.java:484) ~[na:na]
	at java.base/java.net.URL.toExternalForm(URL.java:1001) ~[na:na]
	at java.base/java.net.URL.toString(URL.java:987) ~[na:na]
	at com.openshift.internal.restclient.okhttp.AuthenticatorInterceptor.isUrlWithoutAuthorization(AuthenticatorInterceptor.java:87) ~[openshift-restclient-java-8.1.0.Final.jar:8.1.0.Final]
	at com.openshift.internal.restclient.okhttp.AuthenticatorInterceptor.intercept(AuthenticatorInterceptor.java:61) ~[openshift-restclient-java-8.1.0.Final.jar:8.1.0.Final]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.4.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.4.jar:na]
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:56) ~[openshift-restclient-java-8.1.0.Final.jar:8.1.0.Final]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.4.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.4.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.4.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.4.jar:na]`
`...`

**Comment by adietish** [comment]
Hi @vachillo 
never seen this before even though we're using the client in tools with an oauth token. Maybe you want to give 8.1.1-SNAPSHOT a try which differs significantly from 8.1.0.Final exactly in this area. It might solve your problem.
If not, can you provide some example code that shows me how to replicate this serious flaw?

**Comment by vachillo** [comment]
Thanks @adietish 
I downloaded and installed `8.1.1-SNAPSHOT` and I'm getting the same recursive error. I'm using the ClientBuilder exactly how its written in the documentation. 
I'm calling this client behind a corporate proxy, is there any other configuration i need to consider?

**Comment by adietish** [comment]
@vachillo if your client needs to pass through a proxy you'd have to configure it. The different options are visible in a test that we have: https://github.com/openshift/openshift-restclient-java/blob/master/src/test/java/com/openshift/internal/restclient/okhttp/ClientProxyConnectionTest.java#L42
Hope this helps. 
Nevertheless, an NPE should not occurr and we should fix it. Could you paste the stacktrace that you get when using ```8.1.1-SNAPSHOT```?

**Comment by adietish** [comment]
This looks duplicate to #423 which was fixed in #420 #429. Closing as duplicate. @vachillo please feel free to reopen if you still experience the issue.
