### ISSUE TITLE
list resources on an unreachable server causes NPE

### ISSUE THREAD

**Issue by adietish** [openshift/openshift-restclient-java#424]
in 8.1.1-SNAPSHOT, when one tries to list resources on a server that's not reachable, an NPE is thrown:
```
java.lang.NullPointerException
	at com.openshift.internal.restclient.okhttp.AuthenticatorInterceptor.isUrlWithoutAuthorization(AuthenticatorInterceptor.java:82)
	at com.openshift.internal.restclient.okhttp.AuthenticatorInterceptor.intercept(AuthenticatorInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
	at okhttp3.RealCall.execute(RealCall.kt:66)
	at com.openshift.internal.restclient.ApiTypeMapper.request(ApiTypeMapper.java:273)
	at com.openshift.internal.restclient.ApiTypeMapper.readEndpoint(ApiTypeMapper.java:261)
	at com.openshift.internal.restclient.ApiTypeMapper.getApiGroups(ApiTypeMapper.java:224)
	at com.openshift.internal.restclient.ApiTypeMapper.init(ApiTypeMapper.java:159)
	at com.openshift.internal.restclient.ApiTypeMapper.isSupported(ApiTypeMapper.java:87)
	at com.openshift.internal.restclient.URLBuilder.buildWithNamespaceInPath(URLBuilder.java:148)
	at com.openshift.internal.restclient.URLBuilder.build(URLBuilder.java:135)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:302)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:276)
	at com.openshift.internal.restclient.DefaultClient.execute(DefaultClient.java:265)
	at com.openshift.internal.restclient.DefaultClient.list(DefaultClient.java:172)
	at com.openshift.internal.restclient.DefaultClient.list(DefaultClient.java:161)
	at com.openshift.internal.restclient.DefaultClient.list(DefaultClient.java:152)
```

**Comment by adietish** [comment]
fixed by #425
